/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace PixelOrbitShip {
  export type ShipStatsStruct = {
    hp: BigNumberish;
    maxEnergy: BigNumberish;
    energyRegen: BigNumberish;
    laserWidth: BigNumberish;
    laserDamage: BigNumberish;
    bullet: BigNumberish;
    width: BigNumberish;
    height: BigNumberish;
    maxFrame: BigNumberish;
  };

  export type ShipStatsStructOutput = [
    hp: bigint,
    maxEnergy: bigint,
    energyRegen: bigint,
    laserWidth: bigint,
    laserDamage: bigint,
    bullet: bigint,
    width: bigint,
    height: bigint,
    maxFrame: bigint
  ] & {
    hp: bigint;
    maxEnergy: bigint;
    energyRegen: bigint;
    laserWidth: bigint;
    laserDamage: bigint;
    bullet: bigint;
    width: bigint;
    height: bigint;
    maxFrame: bigint;
  };

  export type ShipTypeStruct = {
    name: string;
    price: BigNumberish;
    metadataURI: string;
    stats: PixelOrbitShip.ShipStatsStruct;
  };

  export type ShipTypeStructOutput = [
    name: string,
    price: bigint,
    metadataURI: string,
    stats: PixelOrbitShip.ShipStatsStructOutput
  ] & {
    name: string;
    price: bigint;
    metadataURI: string;
    stats: PixelOrbitShip.ShipStatsStructOutput;
  };
}

export interface PixelOrbitShipInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FLASH_SALE_DISCOUNT_BPS"
      | "PRICE_FRESHNESS_WINDOW"
      | "approve"
      | "asc"
      | "balanceOf"
      | "buyShip"
      | "getApproved"
      | "getShipStarsPrice"
      | "getShipStats"
      | "getShipType"
      | "getShipTypeCount"
      | "isApprovedForAll"
      | "mintBridged"
      | "mintShip"
      | "name"
      | "owner"
      | "ownerOf"
      | "priceOracle"
      | "renounceOwnership"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setApprovalForAll"
      | "setAsc"
      | "setPriceOracle"
      | "setShipMetadataURI"
      | "shipTypes"
      | "stars"
      | "supportsInterface"
      | "symbol"
      | "tokenByIndex"
      | "tokenOfOwnerByIndex"
      | "tokenShipType"
      | "tokenURI"
      | "totalSupply"
      | "transferFrom"
      | "transferOwnership"
      | "withdrawStars"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "ApprovalForAll"
      | "AscUpdated"
      | "OwnershipTransferred"
      | "PriceOracleUpdated"
      | "ShipMetadataUpdated"
      | "ShipMinted"
      | "ShipPurchased"
      | "Transfer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "FLASH_SALE_DISCOUNT_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRICE_FRESHNESS_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "asc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "buyShip",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getShipStarsPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getShipStats",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getShipType",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getShipTypeCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintBridged",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintShip",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "priceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(functionFragment: "setAsc", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "setPriceOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setShipMetadataURI",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "shipTypes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "stars", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenByIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenOfOwnerByIndex",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenShipType",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawStars",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "FLASH_SALE_DISCOUNT_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRICE_FRESHNESS_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "asc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyShip", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getShipStarsPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getShipStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getShipType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getShipTypeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintBridged",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintShip", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAsc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setShipMetadataURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "shipTypes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stars", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenOfOwnerByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenShipType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawStars",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    approved: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    approved: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AscUpdatedEvent {
  export type InputTuple = [asc: AddressLike];
  export type OutputTuple = [asc: string];
  export interface OutputObject {
    asc: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceOracleUpdatedEvent {
  export type InputTuple = [priceOracle: AddressLike];
  export type OutputTuple = [priceOracle: string];
  export interface OutputObject {
    priceOracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ShipMetadataUpdatedEvent {
  export type InputTuple = [shipTypeIndex: BigNumberish, metadataURI: string];
  export type OutputTuple = [shipTypeIndex: bigint, metadataURI: string];
  export interface OutputObject {
    shipTypeIndex: bigint;
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ShipMintedEvent {
  export type InputTuple = [
    to: AddressLike,
    tokenId: BigNumberish,
    shipTypeIndex: BigNumberish
  ];
  export type OutputTuple = [
    to: string,
    tokenId: bigint,
    shipTypeIndex: bigint
  ];
  export interface OutputObject {
    to: string;
    tokenId: bigint;
    shipTypeIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ShipPurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    tokenId: BigNumberish,
    shipTypeIndex: BigNumberish,
    starsPrice: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    tokenId: bigint,
    shipTypeIndex: bigint,
    starsPrice: bigint
  ];
  export interface OutputObject {
    buyer: string;
    tokenId: bigint;
    shipTypeIndex: bigint;
    starsPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PixelOrbitShip extends BaseContract {
  connect(runner?: ContractRunner | null): PixelOrbitShip;
  waitForDeployment(): Promise<this>;

  interface: PixelOrbitShipInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FLASH_SALE_DISCOUNT_BPS: TypedContractMethod<[], [bigint], "view">;

  PRICE_FRESHNESS_WINDOW: TypedContractMethod<[], [bigint], "view">;

  approve: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  asc: TypedContractMethod<[], [string], "view">;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  buyShip: TypedContractMethod<
    [shipTypeIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  getApproved: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getShipStarsPrice: TypedContractMethod<
    [shipTypeIndex: BigNumberish],
    [bigint],
    "view"
  >;

  getShipStats: TypedContractMethod<
    [tokenId: BigNumberish],
    [PixelOrbitShip.ShipStatsStructOutput],
    "view"
  >;

  getShipType: TypedContractMethod<
    [index: BigNumberish],
    [PixelOrbitShip.ShipTypeStructOutput],
    "view"
  >;

  getShipTypeCount: TypedContractMethod<[], [bigint], "view">;

  isApprovedForAll: TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  mintBridged: TypedContractMethod<
    [to: AddressLike, shipTypeIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  mintShip: TypedContractMethod<
    [to: AddressLike, shipTypeIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  priceOracle: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  "safeTransferFrom(address,address,uint256)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  setAsc: TypedContractMethod<[_asc: AddressLike], [void], "nonpayable">;

  setPriceOracle: TypedContractMethod<
    [_priceOracle: AddressLike],
    [void],
    "nonpayable"
  >;

  setShipMetadataURI: TypedContractMethod<
    [shipTypeIndex: BigNumberish, metadataURI: string],
    [void],
    "nonpayable"
  >;

  shipTypes: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, PixelOrbitShip.ShipStatsStructOutput] & {
        name: string;
        price: bigint;
        metadataURI: string;
        stats: PixelOrbitShip.ShipStatsStructOutput;
      }
    ],
    "view"
  >;

  stars: TypedContractMethod<[], [string], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  tokenByIndex: TypedContractMethod<[index: BigNumberish], [bigint], "view">;

  tokenOfOwnerByIndex: TypedContractMethod<
    [owner: AddressLike, index: BigNumberish],
    [bigint],
    "view"
  >;

  tokenShipType: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawStars: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FLASH_SALE_DISCOUNT_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRICE_FRESHNESS_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "asc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "buyShip"
  ): TypedContractMethod<[shipTypeIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getShipStarsPrice"
  ): TypedContractMethod<[shipTypeIndex: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getShipStats"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [PixelOrbitShip.ShipStatsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getShipType"
  ): TypedContractMethod<
    [index: BigNumberish],
    [PixelOrbitShip.ShipTypeStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getShipTypeCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintBridged"
  ): TypedContractMethod<
    [to: AddressLike, shipTypeIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintShip"
  ): TypedContractMethod<
    [to: AddressLike, shipTypeIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "priceOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAsc"
  ): TypedContractMethod<[_asc: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPriceOracle"
  ): TypedContractMethod<[_priceOracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setShipMetadataURI"
  ): TypedContractMethod<
    [shipTypeIndex: BigNumberish, metadataURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shipTypes"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, PixelOrbitShip.ShipStatsStructOutput] & {
        name: string;
        price: bigint;
        metadataURI: string;
        stats: PixelOrbitShip.ShipStatsStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "stars"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenByIndex"
  ): TypedContractMethod<[index: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokenOfOwnerByIndex"
  ): TypedContractMethod<
    [owner: AddressLike, index: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "tokenShipType"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawStars"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "AscUpdated"
  ): TypedContractEvent<
    AscUpdatedEvent.InputTuple,
    AscUpdatedEvent.OutputTuple,
    AscUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PriceOracleUpdated"
  ): TypedContractEvent<
    PriceOracleUpdatedEvent.InputTuple,
    PriceOracleUpdatedEvent.OutputTuple,
    PriceOracleUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ShipMetadataUpdated"
  ): TypedContractEvent<
    ShipMetadataUpdatedEvent.InputTuple,
    ShipMetadataUpdatedEvent.OutputTuple,
    ShipMetadataUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ShipMinted"
  ): TypedContractEvent<
    ShipMintedEvent.InputTuple,
    ShipMintedEvent.OutputTuple,
    ShipMintedEvent.OutputObject
  >;
  getEvent(
    key: "ShipPurchased"
  ): TypedContractEvent<
    ShipPurchasedEvent.InputTuple,
    ShipPurchasedEvent.OutputTuple,
    ShipPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "AscUpdated(address)": TypedContractEvent<
      AscUpdatedEvent.InputTuple,
      AscUpdatedEvent.OutputTuple,
      AscUpdatedEvent.OutputObject
    >;
    AscUpdated: TypedContractEvent<
      AscUpdatedEvent.InputTuple,
      AscUpdatedEvent.OutputTuple,
      AscUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PriceOracleUpdated(address)": TypedContractEvent<
      PriceOracleUpdatedEvent.InputTuple,
      PriceOracleUpdatedEvent.OutputTuple,
      PriceOracleUpdatedEvent.OutputObject
    >;
    PriceOracleUpdated: TypedContractEvent<
      PriceOracleUpdatedEvent.InputTuple,
      PriceOracleUpdatedEvent.OutputTuple,
      PriceOracleUpdatedEvent.OutputObject
    >;

    "ShipMetadataUpdated(uint256,string)": TypedContractEvent<
      ShipMetadataUpdatedEvent.InputTuple,
      ShipMetadataUpdatedEvent.OutputTuple,
      ShipMetadataUpdatedEvent.OutputObject
    >;
    ShipMetadataUpdated: TypedContractEvent<
      ShipMetadataUpdatedEvent.InputTuple,
      ShipMetadataUpdatedEvent.OutputTuple,
      ShipMetadataUpdatedEvent.OutputObject
    >;

    "ShipMinted(address,uint256,uint256)": TypedContractEvent<
      ShipMintedEvent.InputTuple,
      ShipMintedEvent.OutputTuple,
      ShipMintedEvent.OutputObject
    >;
    ShipMinted: TypedContractEvent<
      ShipMintedEvent.InputTuple,
      ShipMintedEvent.OutputTuple,
      ShipMintedEvent.OutputObject
    >;

    "ShipPurchased(address,uint256,uint256,uint256)": TypedContractEvent<
      ShipPurchasedEvent.InputTuple,
      ShipPurchasedEvent.OutputTuple,
      ShipPurchasedEvent.OutputObject
    >;
    ShipPurchased: TypedContractEvent<
      ShipPurchasedEvent.InputTuple,
      ShipPurchasedEvent.OutputTuple,
      ShipPurchasedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
  };
}
