/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockRevertingPriceOracle,
  MockRevertingPriceOracleInterface,
} from "../../../contracts/mocks/MockRevertingPriceOracle";

const _abi = [
  {
    inputs: [],
    name: "answer",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "updatedAt",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080806040523460135760a9908160188239f35b5f80fdfe608060405260043610156010575f80fd5b5f3560e01c80637519ab5014602c576385bb7d6914602c575f80fd5b34603c575f366003190112156040575b5f80fd5b60405162461bcd60e51b815260206004820152600b60248201526a27b930b1b632903237bbb760a91b6044820152606490fdfea2646970667358221220c5dfc0c531da8a7b80f180f2e1402a8ef38af740def0425d6f58f7221b281fa164736f6c634300081a0033";

type MockRevertingPriceOracleConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockRevertingPriceOracleConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockRevertingPriceOracle__factory extends ContractFactory {
  constructor(...args: MockRevertingPriceOracleConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockRevertingPriceOracle & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): MockRevertingPriceOracle__factory {
    return super.connect(runner) as MockRevertingPriceOracle__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockRevertingPriceOracleInterface {
    return new Interface(_abi) as MockRevertingPriceOracleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockRevertingPriceOracle {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MockRevertingPriceOracle;
  }
}
