/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PixelOrbitLeaderboard {
  export type UserStatsViewStruct = {
    addr: AddressLike;
    gamesPlayed: BigNumberish;
    bestScore: BigNumberish;
    spaceship: string;
  };

  export type UserStatsViewStructOutput = [
    addr: string,
    gamesPlayed: bigint,
    bestScore: bigint,
    spaceship: string
  ] & {
    addr: string;
    gamesPlayed: bigint;
    bestScore: bigint;
    spaceship: string;
  };

  export type ShipScoreViewStruct = {
    shipName: string;
    bestScore: BigNumberish;
  };

  export type ShipScoreViewStructOutput = [
    shipName: string,
    bestScore: bigint
  ] & { shipName: string; bestScore: bigint };
}

export interface PixelOrbitLeaderboardInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "asc"
      | "attestedPlayer"
      | "getAllUserStats"
      | "getPlayerShipScores"
      | "getShipBestScore"
      | "getTotalPlayers"
      | "getUserStats"
      | "getUsername"
      | "markAttested"
      | "owner"
      | "renounceOwnership"
      | "setAsc"
      | "setUsername"
      | "submitScore"
      | "transferOwnership"
      | "usernames"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AscUpdated"
      | "OwnershipTransferred"
      | "ScoreSubmitted"
      | "UsernameSet"
  ): EventFragment;

  encodeFunctionData(functionFragment: "asc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "attestedPlayer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllUserStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerShipScores",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getShipBestScore",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalPlayers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUsername",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markAttested",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "setAsc", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "setUsername", values: [string]): string;
  encodeFunctionData(
    functionFragment: "submitScore",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usernames",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "asc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "attestedPlayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllUserStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerShipScores",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getShipBestScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalPlayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUsername",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markAttested",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAsc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setUsername",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usernames", data: BytesLike): Result;
}

export namespace AscUpdatedEvent {
  export type InputTuple = [asc: AddressLike];
  export type OutputTuple = [asc: string];
  export interface OutputObject {
    asc: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreSubmittedEvent {
  export type InputTuple = [
    player: AddressLike,
    score: BigNumberish,
    shipName: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    score: bigint,
    shipName: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    player: string;
    score: bigint;
    shipName: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UsernameSetEvent {
  export type InputTuple = [player: AddressLike, username: string];
  export type OutputTuple = [player: string, username: string];
  export interface OutputObject {
    player: string;
    username: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PixelOrbitLeaderboard extends BaseContract {
  connect(runner?: ContractRunner | null): PixelOrbitLeaderboard;
  waitForDeployment(): Promise<this>;

  interface: PixelOrbitLeaderboardInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  asc: TypedContractMethod<[], [string], "view">;

  attestedPlayer: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getAllUserStats: TypedContractMethod<
    [],
    [PixelOrbitLeaderboard.UserStatsViewStructOutput[]],
    "view"
  >;

  getPlayerShipScores: TypedContractMethod<
    [player: AddressLike],
    [PixelOrbitLeaderboard.ShipScoreViewStructOutput[]],
    "view"
  >;

  getShipBestScore: TypedContractMethod<
    [player: AddressLike, shipName: string],
    [bigint],
    "view"
  >;

  getTotalPlayers: TypedContractMethod<[], [bigint], "view">;

  getUserStats: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, string] & {
        gamesPlayed: bigint;
        bestScore: bigint;
        spaceship: string;
      }
    ],
    "view"
  >;

  getUsername: TypedContractMethod<[player: AddressLike], [string], "view">;

  markAttested: TypedContractMethod<
    [player: AddressLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAsc: TypedContractMethod<[_asc: AddressLike], [void], "nonpayable">;

  setUsername: TypedContractMethod<[username: string], [void], "nonpayable">;

  submitScore: TypedContractMethod<
    [score: BigNumberish, shipName: string],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usernames: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "asc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "attestedPlayer"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getAllUserStats"
  ): TypedContractMethod<
    [],
    [PixelOrbitLeaderboard.UserStatsViewStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayerShipScores"
  ): TypedContractMethod<
    [player: AddressLike],
    [PixelOrbitLeaderboard.ShipScoreViewStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getShipBestScore"
  ): TypedContractMethod<
    [player: AddressLike, shipName: string],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalPlayers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserStats"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, string] & {
        gamesPlayed: bigint;
        bestScore: bigint;
        spaceship: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUsername"
  ): TypedContractMethod<[player: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "markAttested"
  ): TypedContractMethod<[player: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAsc"
  ): TypedContractMethod<[_asc: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setUsername"
  ): TypedContractMethod<[username: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitScore"
  ): TypedContractMethod<
    [score: BigNumberish, shipName: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usernames"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getEvent(
    key: "AscUpdated"
  ): TypedContractEvent<
    AscUpdatedEvent.InputTuple,
    AscUpdatedEvent.OutputTuple,
    AscUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ScoreSubmitted"
  ): TypedContractEvent<
    ScoreSubmittedEvent.InputTuple,
    ScoreSubmittedEvent.OutputTuple,
    ScoreSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "UsernameSet"
  ): TypedContractEvent<
    UsernameSetEvent.InputTuple,
    UsernameSetEvent.OutputTuple,
    UsernameSetEvent.OutputObject
  >;

  filters: {
    "AscUpdated(address)": TypedContractEvent<
      AscUpdatedEvent.InputTuple,
      AscUpdatedEvent.OutputTuple,
      AscUpdatedEvent.OutputObject
    >;
    AscUpdated: TypedContractEvent<
      AscUpdatedEvent.InputTuple,
      AscUpdatedEvent.OutputTuple,
      AscUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ScoreSubmitted(address,uint256,string,uint256)": TypedContractEvent<
      ScoreSubmittedEvent.InputTuple,
      ScoreSubmittedEvent.OutputTuple,
      ScoreSubmittedEvent.OutputObject
    >;
    ScoreSubmitted: TypedContractEvent<
      ScoreSubmittedEvent.InputTuple,
      ScoreSubmittedEvent.OutputTuple,
      ScoreSubmittedEvent.OutputObject
    >;

    "UsernameSet(address,string)": TypedContractEvent<
      UsernameSetEvent.InputTuple,
      UsernameSetEvent.OutputTuple,
      UsernameSetEvent.OutputObject
    >;
    UsernameSet: TypedContractEvent<
      UsernameSetEvent.InputTuple,
      UsernameSetEvent.OutputTuple,
      UsernameSetEvent.OutputObject
    >;
  };
}
