/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as canonicalInterfacesSol from "./CanonicalInterfaces.sol";
export type { canonicalInterfacesSol };
export type { MockBlockProver } from "./MockBlockProver";
export type { OrbitStarsCC } from "./OrbitStarsCC";
export type { PixelOrbitASC } from "./PixelOrbitASC";
export type { PixelOrbitPriceOracle } from "./PixelOrbitPriceOracle";
export type { PixelOrbitSource } from "./PixelOrbitSource";
export type { StarsSale } from "./StarsSale";
export type { StarsSaleCC3 } from "./StarsSaleCC3";
export type { StarsSepolia } from "./StarsSepolia";
