/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace INativeQueryVerifier {
  export type MerkleProofEntryStruct = { hash: BytesLike; isLeft: boolean };

  export type MerkleProofEntryStructOutput = [hash: string, isLeft: boolean] & {
    hash: string;
    isLeft: boolean;
  };

  export type MerkleProofStruct = {
    root: BytesLike;
    siblings: INativeQueryVerifier.MerkleProofEntryStruct[];
  };

  export type MerkleProofStructOutput = [
    root: string,
    siblings: INativeQueryVerifier.MerkleProofEntryStructOutput[]
  ] & {
    root: string;
    siblings: INativeQueryVerifier.MerkleProofEntryStructOutput[];
  };

  export type ContinuityProofStruct = {
    lowerEndpointDigest: BytesLike;
    roots: BytesLike[];
  };

  export type ContinuityProofStructOutput = [
    lowerEndpointDigest: string,
    roots: string[]
  ] & { lowerEndpointDigest: string; roots: string[] };
}

export interface MockBlockProverInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "configured"
      | "defaultResult"
      | "results"
      | "setResult"
      | "setResultForTx"
      | "verify(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))"
      | "verify(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "configured",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultResult",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "results", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "setResult", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "setResultForTx",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "verify(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))",
    values: [
      BigNumberish,
      BigNumberish[],
      BytesLike[],
      INativeQueryVerifier.MerkleProofStruct[],
      INativeQueryVerifier.ContinuityProofStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verify(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))",
    values: [
      BigNumberish,
      BigNumberish,
      BytesLike,
      INativeQueryVerifier.MerkleProofStruct,
      INativeQueryVerifier.ContinuityProofStruct
    ]
  ): string;

  decodeFunctionResult(functionFragment: "configured", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "defaultResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "results", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setResult", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setResultForTx",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verify(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verify(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))",
    data: BytesLike
  ): Result;
}

export interface MockBlockProver extends BaseContract {
  connect(runner?: ContractRunner | null): MockBlockProver;
  waitForDeployment(): Promise<this>;

  interface: MockBlockProverInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  configured: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  defaultResult: TypedContractMethod<[], [boolean], "view">;

  results: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  setResult: TypedContractMethod<[ok: boolean], [void], "nonpayable">;

  setResultForTx: TypedContractMethod<
    [txBytes: BytesLike, ok: boolean],
    [void],
    "nonpayable"
  >;

  "verify(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))": TypedContractMethod<
    [
      arg0: BigNumberish,
      heights: BigNumberish[],
      encodedTransactions: BytesLike[],
      merkleProofs: INativeQueryVerifier.MerkleProofStruct[],
      arg4: INativeQueryVerifier.ContinuityProofStruct
    ],
    [boolean],
    "view"
  >;

  "verify(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))": TypedContractMethod<
    [
      arg0: BigNumberish,
      arg1: BigNumberish,
      encodedTransaction: BytesLike,
      arg3: INativeQueryVerifier.MerkleProofStruct,
      arg4: INativeQueryVerifier.ContinuityProofStruct
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "configured"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "defaultResult"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "results"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "setResult"
  ): TypedContractMethod<[ok: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setResultForTx"
  ): TypedContractMethod<
    [txBytes: BytesLike, ok: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verify(uint64,uint64[],bytes[],(bytes32,(bytes32,bool)[])[],(bytes32,bytes32[]))"
  ): TypedContractMethod<
    [
      arg0: BigNumberish,
      heights: BigNumberish[],
      encodedTransactions: BytesLike[],
      merkleProofs: INativeQueryVerifier.MerkleProofStruct[],
      arg4: INativeQueryVerifier.ContinuityProofStruct
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "verify(uint64,uint64,bytes,(bytes32,(bytes32,bool)[]),(bytes32,bytes32[]))"
  ): TypedContractMethod<
    [
      arg0: BigNumberish,
      arg1: BigNumberish,
      encodedTransaction: BytesLike,
      arg3: INativeQueryVerifier.MerkleProofStruct,
      arg4: INativeQueryVerifier.ContinuityProofStruct
    ],
    [boolean],
    "view"
  >;

  filters: {};
}
