/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PixelOrbitSourceInterface extends Interface {
  getFunction(
    nameOrSignature: "lock" | "stars" | "usedNonces"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "StarsLocked"): EventFragment;

  encodeFunctionData(
    functionFragment: "lock",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "stars", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "usedNonces",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "lock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stars", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usedNonces", data: BytesLike): Result;
}

export namespace StarsLockedEvent {
  export type InputTuple = [
    player: AddressLike,
    amount: BigNumberish,
    nonce: BigNumberish,
    creditcoinRecipient: AddressLike
  ];
  export type OutputTuple = [
    player: string,
    amount: bigint,
    nonce: bigint,
    creditcoinRecipient: string
  ];
  export interface OutputObject {
    player: string;
    amount: bigint;
    nonce: bigint;
    creditcoinRecipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PixelOrbitSource extends BaseContract {
  connect(runner?: ContractRunner | null): PixelOrbitSource;
  waitForDeployment(): Promise<this>;

  interface: PixelOrbitSourceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  lock: TypedContractMethod<
    [
      amount: BigNumberish,
      nonce: BigNumberish,
      creditcoinRecipient: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  stars: TypedContractMethod<[], [string], "view">;

  usedNonces: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "lock"
  ): TypedContractMethod<
    [
      amount: BigNumberish,
      nonce: BigNumberish,
      creditcoinRecipient: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stars"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usedNonces"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  getEvent(
    key: "StarsLocked"
  ): TypedContractEvent<
    StarsLockedEvent.InputTuple,
    StarsLockedEvent.OutputTuple,
    StarsLockedEvent.OutputObject
  >;

  filters: {
    "StarsLocked(address,uint256,uint256,address)": TypedContractEvent<
      StarsLockedEvent.InputTuple,
      StarsLockedEvent.OutputTuple,
      StarsLockedEvent.OutputObject
    >;
    StarsLocked: TypedContractEvent<
      StarsLockedEvent.InputTuple,
      StarsLockedEvent.OutputTuple,
      StarsLockedEvent.OutputObject
    >;
  };
}
