/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace EvmV1Decoder {
  export type LogEntryStruct = {
    address_: AddressLike;
    topics: BytesLike[];
    data: BytesLike;
  };

  export type LogEntryStructOutput = [
    address_: string,
    topics: string[],
    data: string
  ] & { address_: string; topics: string[]; data: string };

  export type ReceiptFieldsStruct = {
    receiptStatus: BigNumberish;
    receiptGasUsed: BigNumberish;
    receiptLogs: EvmV1Decoder.LogEntryStruct[];
    receiptLogsBloom: BytesLike;
  };

  export type ReceiptFieldsStructOutput = [
    receiptStatus: bigint,
    receiptGasUsed: bigint,
    receiptLogs: EvmV1Decoder.LogEntryStructOutput[],
    receiptLogsBloom: string
  ] & {
    receiptStatus: bigint;
    receiptGasUsed: bigint;
    receiptLogs: EvmV1Decoder.LogEntryStructOutput[];
    receiptLogsBloom: string;
  };
}

export declare namespace INativeQueryVerifier {
  export type MerkleProofEntryStruct = { hash: BytesLike; isLeft: boolean };

  export type MerkleProofEntryStructOutput = [hash: string, isLeft: boolean] & {
    hash: string;
    isLeft: boolean;
  };
}

export interface PixelOrbitPriceOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ANSWER_UPDATED_SIG"
      | "answer"
      | "blockProver"
      | "decodeReceipt"
      | "feedEmitters"
      | "owner"
      | "renounceOwnership"
      | "roundId"
      | "setFeedEmitter"
      | "sourceChainKey"
      | "transferOwnership"
      | "updatePrice"
      | "updatedAt"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PriceFeedUpdated"
      | "PriceUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ANSWER_UPDATED_SIG",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "answer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "blockProver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "decodeReceipt",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "feedEmitters",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "roundId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setFeedEmitter",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "sourceChainKey",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePrice",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      INativeQueryVerifier.MerkleProofEntryStruct[],
      BytesLike,
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(functionFragment: "updatedAt", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "ANSWER_UPDATED_SIG",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "answer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "blockProver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decodeReceipt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feedEmitters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "roundId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFeedEmitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sourceChainKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updatedAt", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceFeedUpdatedEvent {
  export type InputTuple = [emitter: AddressLike, allowed: boolean];
  export type OutputTuple = [emitter: string, allowed: boolean];
  export interface OutputObject {
    emitter: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceUpdatedEvent {
  export type InputTuple = [
    answer: BigNumberish,
    roundId: BigNumberish,
    updatedAt: BigNumberish
  ];
  export type OutputTuple = [
    answer: bigint,
    roundId: bigint,
    updatedAt: bigint
  ];
  export interface OutputObject {
    answer: bigint;
    roundId: bigint;
    updatedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PixelOrbitPriceOracle extends BaseContract {
  connect(runner?: ContractRunner | null): PixelOrbitPriceOracle;
  waitForDeployment(): Promise<this>;

  interface: PixelOrbitPriceOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ANSWER_UPDATED_SIG: TypedContractMethod<[], [string], "view">;

  answer: TypedContractMethod<[], [bigint], "view">;

  blockProver: TypedContractMethod<[], [string], "view">;

  decodeReceipt: TypedContractMethod<
    [txBytes: BytesLike],
    [EvmV1Decoder.ReceiptFieldsStructOutput],
    "view"
  >;

  feedEmitters: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  roundId: TypedContractMethod<[], [bigint], "view">;

  setFeedEmitter: TypedContractMethod<
    [emitter: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  sourceChainKey: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updatePrice: TypedContractMethod<
    [
      action: BigNumberish,
      chainKey: BigNumberish,
      height: BigNumberish,
      txBytes: BytesLike,
      root: BytesLike,
      siblings: INativeQueryVerifier.MerkleProofEntryStruct[],
      digest: BytesLike,
      roots: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  updatedAt: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ANSWER_UPDATED_SIG"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "answer"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "blockProver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "decodeReceipt"
  ): TypedContractMethod<
    [txBytes: BytesLike],
    [EvmV1Decoder.ReceiptFieldsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "feedEmitters"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "roundId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setFeedEmitter"
  ): TypedContractMethod<
    [emitter: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sourceChainKey"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePrice"
  ): TypedContractMethod<
    [
      action: BigNumberish,
      chainKey: BigNumberish,
      height: BigNumberish,
      txBytes: BytesLike,
      root: BytesLike,
      siblings: INativeQueryVerifier.MerkleProofEntryStruct[],
      digest: BytesLike,
      roots: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updatedAt"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PriceFeedUpdated"
  ): TypedContractEvent<
    PriceFeedUpdatedEvent.InputTuple,
    PriceFeedUpdatedEvent.OutputTuple,
    PriceFeedUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PriceUpdated"
  ): TypedContractEvent<
    PriceUpdatedEvent.InputTuple,
    PriceUpdatedEvent.OutputTuple,
    PriceUpdatedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PriceFeedUpdated(address,bool)": TypedContractEvent<
      PriceFeedUpdatedEvent.InputTuple,
      PriceFeedUpdatedEvent.OutputTuple,
      PriceFeedUpdatedEvent.OutputObject
    >;
    PriceFeedUpdated: TypedContractEvent<
      PriceFeedUpdatedEvent.InputTuple,
      PriceFeedUpdatedEvent.OutputTuple,
      PriceFeedUpdatedEvent.OutputObject
    >;

    "PriceUpdated(int256,uint256,uint256)": TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
    PriceUpdated: TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
  };
}
