/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace EvmV1Decoder {
  export type CommonTxFieldsStruct = {
    nonce: BigNumberish;
    gasLimit: BigNumberish;
    from: AddressLike;
    toIsNull: boolean;
    to: AddressLike;
    value: BigNumberish;
    data: BytesLike;
  };

  export type CommonTxFieldsStructOutput = [
    nonce: bigint,
    gasLimit: bigint,
    from: string,
    toIsNull: boolean,
    to: string,
    value: bigint,
    data: string
  ] & {
    nonce: bigint;
    gasLimit: bigint;
    from: string;
    toIsNull: boolean;
    to: string;
    value: bigint;
    data: string;
  };

  export type LogEntryStruct = {
    address_: AddressLike;
    topics: BytesLike[];
    data: BytesLike;
  };

  export type LogEntryStructOutput = [
    address_: string,
    topics: string[],
    data: string
  ] & { address_: string; topics: string[]; data: string };

  export type ReceiptFieldsStruct = {
    receiptStatus: BigNumberish;
    receiptGasUsed: BigNumberish;
    receiptLogs: EvmV1Decoder.LogEntryStruct[];
    receiptLogsBloom: BytesLike;
  };

  export type ReceiptFieldsStructOutput = [
    receiptStatus: bigint,
    receiptGasUsed: bigint,
    receiptLogs: EvmV1Decoder.LogEntryStructOutput[],
    receiptLogsBloom: string
  ] & {
    receiptStatus: bigint;
    receiptGasUsed: bigint;
    receiptLogs: EvmV1Decoder.LogEntryStructOutput[];
    receiptLogsBloom: string;
  };
}

export declare namespace INativeQueryVerifier {
  export type MerkleProofEntryStruct = { hash: BytesLike; isLeft: boolean };

  export type MerkleProofEntryStructOutput = [hash: string, isLeft: boolean] & {
    hash: string;
    isLeft: boolean;
  };

  export type MerkleProofStruct = {
    root: BytesLike;
    siblings: INativeQueryVerifier.MerkleProofEntryStruct[];
  };

  export type MerkleProofStructOutput = [
    root: string,
    siblings: INativeQueryVerifier.MerkleProofEntryStructOutput[]
  ] & {
    root: string;
    siblings: INativeQueryVerifier.MerkleProofEntryStructOutput[];
  };
}

export interface PixelOrbitASCInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "LOCK_CALLDATA_LENGTH"
      | "LOCK_SELECTOR"
      | "MAX_BATCH_LOCKS"
      | "blockProver"
      | "decodeForBatch"
      | "execute"
      | "executeBatch"
      | "executedLocks"
      | "item"
      | "leaderboard"
      | "owner"
      | "renounceOwnership"
      | "setItem"
      | "setShip"
      | "ship"
      | "source"
      | "sourceChainKey"
      | "starsCC"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BridgeBatchExecuted"
      | "BridgeExecuted"
      | "ItemUpdated"
      | "OwnershipTransferred"
      | "ShipUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "LOCK_CALLDATA_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOCK_SELECTOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_BATCH_LOCKS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "blockProver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "decodeForBatch",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      INativeQueryVerifier.MerkleProofEntryStruct[],
      BytesLike,
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeBatch",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish[],
      BytesLike[],
      INativeQueryVerifier.MerkleProofStruct[],
      BytesLike,
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executedLocks",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "item", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "leaderboard",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setItem",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setShip",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "ship", values?: undefined): string;
  encodeFunctionData(functionFragment: "source", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "sourceChainKey",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "starsCC", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "LOCK_CALLDATA_LENGTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LOCK_SELECTOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_BATCH_LOCKS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blockProver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decodeForBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executedLocks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "item", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "leaderboard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setItem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setShip", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ship", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "source", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sourceChainKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "starsCC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace BridgeBatchExecutedEvent {
  export type InputTuple = [
    index: BigNumberish,
    success: boolean,
    reason: BytesLike
  ];
  export type OutputTuple = [index: bigint, success: boolean, reason: string];
  export interface OutputObject {
    index: bigint;
    success: boolean;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BridgeExecutedEvent {
  export type InputTuple = [
    player: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish,
    nonce: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    recipient: string,
    amount: bigint,
    nonce: bigint
  ];
  export interface OutputObject {
    player: string;
    recipient: string;
    amount: bigint;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ItemUpdatedEvent {
  export type InputTuple = [item: AddressLike];
  export type OutputTuple = [item: string];
  export interface OutputObject {
    item: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ShipUpdatedEvent {
  export type InputTuple = [ship: AddressLike];
  export type OutputTuple = [ship: string];
  export interface OutputObject {
    ship: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PixelOrbitASC extends BaseContract {
  connect(runner?: ContractRunner | null): PixelOrbitASC;
  waitForDeployment(): Promise<this>;

  interface: PixelOrbitASCInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LOCK_CALLDATA_LENGTH: TypedContractMethod<[], [bigint], "view">;

  LOCK_SELECTOR: TypedContractMethod<[], [string], "view">;

  MAX_BATCH_LOCKS: TypedContractMethod<[], [bigint], "view">;

  blockProver: TypedContractMethod<[], [string], "view">;

  decodeForBatch: TypedContractMethod<
    [txBytes: BytesLike],
    [
      [
        EvmV1Decoder.CommonTxFieldsStructOutput,
        EvmV1Decoder.ReceiptFieldsStructOutput
      ] & {
        common: EvmV1Decoder.CommonTxFieldsStructOutput;
        receipt: EvmV1Decoder.ReceiptFieldsStructOutput;
      }
    ],
    "view"
  >;

  execute: TypedContractMethod<
    [
      action: BigNumberish,
      chainKey: BigNumberish,
      height: BigNumberish,
      txBytes: BytesLike,
      root: BytesLike,
      siblings: INativeQueryVerifier.MerkleProofEntryStruct[],
      digest: BytesLike,
      roots: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  executeBatch: TypedContractMethod<
    [
      action: BigNumberish,
      chainKey: BigNumberish,
      heights: BigNumberish[],
      txBytesArray: BytesLike[],
      merkleProofs: INativeQueryVerifier.MerkleProofStruct[],
      digest: BytesLike,
      continuityRoots: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  executedLocks: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  item: TypedContractMethod<[], [string], "view">;

  leaderboard: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setItem: TypedContractMethod<[_item: AddressLike], [void], "nonpayable">;

  setShip: TypedContractMethod<[_ship: AddressLike], [void], "nonpayable">;

  ship: TypedContractMethod<[], [string], "view">;

  source: TypedContractMethod<[], [string], "view">;

  sourceChainKey: TypedContractMethod<[], [bigint], "view">;

  starsCC: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LOCK_CALLDATA_LENGTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LOCK_SELECTOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_BATCH_LOCKS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "blockProver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "decodeForBatch"
  ): TypedContractMethod<
    [txBytes: BytesLike],
    [
      [
        EvmV1Decoder.CommonTxFieldsStructOutput,
        EvmV1Decoder.ReceiptFieldsStructOutput
      ] & {
        common: EvmV1Decoder.CommonTxFieldsStructOutput;
        receipt: EvmV1Decoder.ReceiptFieldsStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [
      action: BigNumberish,
      chainKey: BigNumberish,
      height: BigNumberish,
      txBytes: BytesLike,
      root: BytesLike,
      siblings: INativeQueryVerifier.MerkleProofEntryStruct[],
      digest: BytesLike,
      roots: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeBatch"
  ): TypedContractMethod<
    [
      action: BigNumberish,
      chainKey: BigNumberish,
      heights: BigNumberish[],
      txBytesArray: BytesLike[],
      merkleProofs: INativeQueryVerifier.MerkleProofStruct[],
      digest: BytesLike,
      continuityRoots: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executedLocks"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "item"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "leaderboard"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setItem"
  ): TypedContractMethod<[_item: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setShip"
  ): TypedContractMethod<[_ship: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "ship"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "source"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "sourceChainKey"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "starsCC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "BridgeBatchExecuted"
  ): TypedContractEvent<
    BridgeBatchExecutedEvent.InputTuple,
    BridgeBatchExecutedEvent.OutputTuple,
    BridgeBatchExecutedEvent.OutputObject
  >;
  getEvent(
    key: "BridgeExecuted"
  ): TypedContractEvent<
    BridgeExecutedEvent.InputTuple,
    BridgeExecutedEvent.OutputTuple,
    BridgeExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ItemUpdated"
  ): TypedContractEvent<
    ItemUpdatedEvent.InputTuple,
    ItemUpdatedEvent.OutputTuple,
    ItemUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ShipUpdated"
  ): TypedContractEvent<
    ShipUpdatedEvent.InputTuple,
    ShipUpdatedEvent.OutputTuple,
    ShipUpdatedEvent.OutputObject
  >;

  filters: {
    "BridgeBatchExecuted(uint256,bool,bytes)": TypedContractEvent<
      BridgeBatchExecutedEvent.InputTuple,
      BridgeBatchExecutedEvent.OutputTuple,
      BridgeBatchExecutedEvent.OutputObject
    >;
    BridgeBatchExecuted: TypedContractEvent<
      BridgeBatchExecutedEvent.InputTuple,
      BridgeBatchExecutedEvent.OutputTuple,
      BridgeBatchExecutedEvent.OutputObject
    >;

    "BridgeExecuted(address,address,uint256,uint256)": TypedContractEvent<
      BridgeExecutedEvent.InputTuple,
      BridgeExecutedEvent.OutputTuple,
      BridgeExecutedEvent.OutputObject
    >;
    BridgeExecuted: TypedContractEvent<
      BridgeExecutedEvent.InputTuple,
      BridgeExecutedEvent.OutputTuple,
      BridgeExecutedEvent.OutputObject
    >;

    "ItemUpdated(address)": TypedContractEvent<
      ItemUpdatedEvent.InputTuple,
      ItemUpdatedEvent.OutputTuple,
      ItemUpdatedEvent.OutputObject
    >;
    ItemUpdated: TypedContractEvent<
      ItemUpdatedEvent.InputTuple,
      ItemUpdatedEvent.OutputTuple,
      ItemUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ShipUpdated(address)": TypedContractEvent<
      ShipUpdatedEvent.InputTuple,
      ShipUpdatedEvent.OutputTuple,
      ShipUpdatedEvent.OutputObject
    >;
    ShipUpdated: TypedContractEvent<
      ShipUpdatedEvent.InputTuple,
      ShipUpdatedEvent.OutputTuple,
      ShipUpdatedEvent.OutputObject
    >;
  };
}
