/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface StarsSaleCC3Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "buy"
      | "cancelConsignment"
      | "consigned"
      | "depositStars"
      | "escrowedStars"
      | "lotHead"
      | "lots"
      | "owner"
      | "pricePerStar"
      | "proceeds"
      | "renounceOwnership"
      | "sellPricePerStar"
      | "sellStars"
      | "setPrice"
      | "setSellPrice"
      | "stars"
      | "totalProceedsOwed"
      | "transferOwnership"
      | "withdrawFunds"
      | "withdrawProceeds"
      | "withdrawStars"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConsignmentCancelled"
      | "ConsignmentFilled"
      | "FundsWithdrawn"
      | "OwnershipTransferred"
      | "PriceUpdated"
      | "ProceedsWithdrawn"
      | "StarsDeposited"
      | "StarsPurchased"
      | "StarsSold"
      | "StarsWithdrawn"
  ): EventFragment;

  encodeFunctionData(functionFragment: "buy", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "cancelConsignment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "consigned",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositStars",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "escrowedStars",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lotHead", values?: undefined): string;
  encodeFunctionData(functionFragment: "lots", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pricePerStar",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proceeds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sellPricePerStar",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sellStars",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSellPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "stars", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalProceedsOwed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFunds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawProceeds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawStars",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelConsignment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "consigned", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositStars",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escrowedStars",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lotHead", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lots", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pricePerStar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proceeds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sellPricePerStar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sellStars", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setSellPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stars", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalProceedsOwed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawProceeds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawStars",
    data: BytesLike
  ): Result;
}

export namespace ConsignmentCancelledEvent {
  export type InputTuple = [
    depositor: AddressLike,
    lotId: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [depositor: string, lotId: bigint, amount: bigint];
  export interface OutputObject {
    depositor: string;
    lotId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConsignmentFilledEvent {
  export type InputTuple = [
    lotId: BigNumberish,
    seller: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [lotId: bigint, seller: string, amount: bigint];
  export interface OutputObject {
    lotId: bigint;
    seller: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceUpdatedEvent {
  export type InputTuple = [oldPrice: BigNumberish, newPrice: BigNumberish];
  export type OutputTuple = [oldPrice: bigint, newPrice: bigint];
  export interface OutputObject {
    oldPrice: bigint;
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProceedsWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StarsDepositedEvent {
  export type InputTuple = [
    depositor: AddressLike,
    starAmount: BigNumberish,
    lotId: BigNumberish
  ];
  export type OutputTuple = [
    depositor: string,
    starAmount: bigint,
    lotId: bigint
  ];
  export interface OutputObject {
    depositor: string;
    starAmount: bigint;
    lotId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StarsPurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    starAmount: BigNumberish,
    paid: BigNumberish
  ];
  export type OutputTuple = [buyer: string, starAmount: bigint, paid: bigint];
  export interface OutputObject {
    buyer: string;
    starAmount: bigint;
    paid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StarsSoldEvent {
  export type InputTuple = [
    seller: AddressLike,
    starAmount: BigNumberish,
    payout: BigNumberish
  ];
  export type OutputTuple = [
    seller: string,
    starAmount: bigint,
    payout: bigint
  ];
  export interface OutputObject {
    seller: string;
    starAmount: bigint;
    payout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StarsWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StarsSaleCC3 extends BaseContract {
  connect(runner?: ContractRunner | null): StarsSaleCC3;
  waitForDeployment(): Promise<this>;

  interface: StarsSaleCC3Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buy: TypedContractMethod<[starAmount: BigNumberish], [void], "payable">;

  cancelConsignment: TypedContractMethod<
    [lotId: BigNumberish],
    [void],
    "nonpayable"
  >;

  consigned: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  depositStars: TypedContractMethod<
    [starAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  escrowedStars: TypedContractMethod<[], [bigint], "view">;

  lotHead: TypedContractMethod<[], [bigint], "view">;

  lots: TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { seller: string; remaining: bigint }],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pricePerStar: TypedContractMethod<[], [bigint], "view">;

  proceeds: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sellPricePerStar: TypedContractMethod<[], [bigint], "view">;

  sellStars: TypedContractMethod<
    [starAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPrice: TypedContractMethod<
    [_pricePerStar: BigNumberish],
    [void],
    "nonpayable"
  >;

  setSellPrice: TypedContractMethod<
    [_sellPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  stars: TypedContractMethod<[], [string], "view">;

  totalProceedsOwed: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawFunds: TypedContractMethod<[to: AddressLike], [void], "nonpayable">;

  withdrawProceeds: TypedContractMethod<[], [void], "nonpayable">;

  withdrawStars: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buy"
  ): TypedContractMethod<[starAmount: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "cancelConsignment"
  ): TypedContractMethod<[lotId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "consigned"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositStars"
  ): TypedContractMethod<[starAmount: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "escrowedStars"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lotHead"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lots"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { seller: string; remaining: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pricePerStar"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proceeds"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sellPricePerStar"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "sellStars"
  ): TypedContractMethod<[starAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPrice"
  ): TypedContractMethod<[_pricePerStar: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSellPrice"
  ): TypedContractMethod<[_sellPrice: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stars"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalProceedsOwed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFunds"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawProceeds"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawStars"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ConsignmentCancelled"
  ): TypedContractEvent<
    ConsignmentCancelledEvent.InputTuple,
    ConsignmentCancelledEvent.OutputTuple,
    ConsignmentCancelledEvent.OutputObject
  >;
  getEvent(
    key: "ConsignmentFilled"
  ): TypedContractEvent<
    ConsignmentFilledEvent.InputTuple,
    ConsignmentFilledEvent.OutputTuple,
    ConsignmentFilledEvent.OutputObject
  >;
  getEvent(
    key: "FundsWithdrawn"
  ): TypedContractEvent<
    FundsWithdrawnEvent.InputTuple,
    FundsWithdrawnEvent.OutputTuple,
    FundsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PriceUpdated"
  ): TypedContractEvent<
    PriceUpdatedEvent.InputTuple,
    PriceUpdatedEvent.OutputTuple,
    PriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ProceedsWithdrawn"
  ): TypedContractEvent<
    ProceedsWithdrawnEvent.InputTuple,
    ProceedsWithdrawnEvent.OutputTuple,
    ProceedsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "StarsDeposited"
  ): TypedContractEvent<
    StarsDepositedEvent.InputTuple,
    StarsDepositedEvent.OutputTuple,
    StarsDepositedEvent.OutputObject
  >;
  getEvent(
    key: "StarsPurchased"
  ): TypedContractEvent<
    StarsPurchasedEvent.InputTuple,
    StarsPurchasedEvent.OutputTuple,
    StarsPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "StarsSold"
  ): TypedContractEvent<
    StarsSoldEvent.InputTuple,
    StarsSoldEvent.OutputTuple,
    StarsSoldEvent.OutputObject
  >;
  getEvent(
    key: "StarsWithdrawn"
  ): TypedContractEvent<
    StarsWithdrawnEvent.InputTuple,
    StarsWithdrawnEvent.OutputTuple,
    StarsWithdrawnEvent.OutputObject
  >;

  filters: {
    "ConsignmentCancelled(address,uint256,uint256)": TypedContractEvent<
      ConsignmentCancelledEvent.InputTuple,
      ConsignmentCancelledEvent.OutputTuple,
      ConsignmentCancelledEvent.OutputObject
    >;
    ConsignmentCancelled: TypedContractEvent<
      ConsignmentCancelledEvent.InputTuple,
      ConsignmentCancelledEvent.OutputTuple,
      ConsignmentCancelledEvent.OutputObject
    >;

    "ConsignmentFilled(uint256,address,uint256)": TypedContractEvent<
      ConsignmentFilledEvent.InputTuple,
      ConsignmentFilledEvent.OutputTuple,
      ConsignmentFilledEvent.OutputObject
    >;
    ConsignmentFilled: TypedContractEvent<
      ConsignmentFilledEvent.InputTuple,
      ConsignmentFilledEvent.OutputTuple,
      ConsignmentFilledEvent.OutputObject
    >;

    "FundsWithdrawn(address,uint256)": TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;
    FundsWithdrawn: TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PriceUpdated(uint256,uint256)": TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
    PriceUpdated: TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;

    "ProceedsWithdrawn(address,uint256)": TypedContractEvent<
      ProceedsWithdrawnEvent.InputTuple,
      ProceedsWithdrawnEvent.OutputTuple,
      ProceedsWithdrawnEvent.OutputObject
    >;
    ProceedsWithdrawn: TypedContractEvent<
      ProceedsWithdrawnEvent.InputTuple,
      ProceedsWithdrawnEvent.OutputTuple,
      ProceedsWithdrawnEvent.OutputObject
    >;

    "StarsDeposited(address,uint256,uint256)": TypedContractEvent<
      StarsDepositedEvent.InputTuple,
      StarsDepositedEvent.OutputTuple,
      StarsDepositedEvent.OutputObject
    >;
    StarsDeposited: TypedContractEvent<
      StarsDepositedEvent.InputTuple,
      StarsDepositedEvent.OutputTuple,
      StarsDepositedEvent.OutputObject
    >;

    "StarsPurchased(address,uint256,uint256)": TypedContractEvent<
      StarsPurchasedEvent.InputTuple,
      StarsPurchasedEvent.OutputTuple,
      StarsPurchasedEvent.OutputObject
    >;
    StarsPurchased: TypedContractEvent<
      StarsPurchasedEvent.InputTuple,
      StarsPurchasedEvent.OutputTuple,
      StarsPurchasedEvent.OutputObject
    >;

    "StarsSold(address,uint256,uint256)": TypedContractEvent<
      StarsSoldEvent.InputTuple,
      StarsSoldEvent.OutputTuple,
      StarsSoldEvent.OutputObject
    >;
    StarsSold: TypedContractEvent<
      StarsSoldEvent.InputTuple,
      StarsSoldEvent.OutputTuple,
      StarsSoldEvent.OutputObject
    >;

    "StarsWithdrawn(address,uint256)": TypedContractEvent<
      StarsWithdrawnEvent.InputTuple,
      StarsWithdrawnEvent.OutputTuple,
      StarsWithdrawnEvent.OutputObject
    >;
    StarsWithdrawn: TypedContractEvent<
      StarsWithdrawnEvent.InputTuple,
      StarsWithdrawnEvent.OutputTuple,
      StarsWithdrawnEvent.OutputObject
    >;
  };
}
