/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface StarsSaleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_PER_TX"
      | "buy"
      | "owner"
      | "pricePerStar"
      | "renounceOwnership"
      | "setPrice"
      | "stars"
      | "transferOwnership"
      | "withdrawETH"
      | "withdrawStars"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ETHWithdrawn"
      | "OwnershipTransferred"
      | "PriceUpdated"
      | "StarsPurchased"
      | "StarsWithdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_PER_TX",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "buy", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pricePerStar",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "stars", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawETH",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawStars",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "MAX_PER_TX", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pricePerStar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stars", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawStars",
    data: BytesLike
  ): Result;
}

export namespace ETHWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceUpdatedEvent {
  export type InputTuple = [oldPrice: BigNumberish, newPrice: BigNumberish];
  export type OutputTuple = [oldPrice: bigint, newPrice: bigint];
  export interface OutputObject {
    oldPrice: bigint;
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StarsPurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    starAmount: BigNumberish,
    paid: BigNumberish
  ];
  export type OutputTuple = [buyer: string, starAmount: bigint, paid: bigint];
  export interface OutputObject {
    buyer: string;
    starAmount: bigint;
    paid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StarsWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StarsSale extends BaseContract {
  connect(runner?: ContractRunner | null): StarsSale;
  waitForDeployment(): Promise<this>;

  interface: StarsSaleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_PER_TX: TypedContractMethod<[], [bigint], "view">;

  buy: TypedContractMethod<[starAmount: BigNumberish], [void], "payable">;

  owner: TypedContractMethod<[], [string], "view">;

  pricePerStar: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setPrice: TypedContractMethod<
    [_pricePerStar: BigNumberish],
    [void],
    "nonpayable"
  >;

  stars: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawETH: TypedContractMethod<[to: AddressLike], [void], "nonpayable">;

  withdrawStars: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_PER_TX"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "buy"
  ): TypedContractMethod<[starAmount: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pricePerStar"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPrice"
  ): TypedContractMethod<[_pricePerStar: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stars"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawETH"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawStars"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ETHWithdrawn"
  ): TypedContractEvent<
    ETHWithdrawnEvent.InputTuple,
    ETHWithdrawnEvent.OutputTuple,
    ETHWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PriceUpdated"
  ): TypedContractEvent<
    PriceUpdatedEvent.InputTuple,
    PriceUpdatedEvent.OutputTuple,
    PriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "StarsPurchased"
  ): TypedContractEvent<
    StarsPurchasedEvent.InputTuple,
    StarsPurchasedEvent.OutputTuple,
    StarsPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "StarsWithdrawn"
  ): TypedContractEvent<
    StarsWithdrawnEvent.InputTuple,
    StarsWithdrawnEvent.OutputTuple,
    StarsWithdrawnEvent.OutputObject
  >;

  filters: {
    "ETHWithdrawn(address,uint256)": TypedContractEvent<
      ETHWithdrawnEvent.InputTuple,
      ETHWithdrawnEvent.OutputTuple,
      ETHWithdrawnEvent.OutputObject
    >;
    ETHWithdrawn: TypedContractEvent<
      ETHWithdrawnEvent.InputTuple,
      ETHWithdrawnEvent.OutputTuple,
      ETHWithdrawnEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PriceUpdated(uint256,uint256)": TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
    PriceUpdated: TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;

    "StarsPurchased(address,uint256,uint256)": TypedContractEvent<
      StarsPurchasedEvent.InputTuple,
      StarsPurchasedEvent.OutputTuple,
      StarsPurchasedEvent.OutputObject
    >;
    StarsPurchased: TypedContractEvent<
      StarsPurchasedEvent.InputTuple,
      StarsPurchasedEvent.OutputTuple,
      StarsPurchasedEvent.OutputObject
    >;

    "StarsWithdrawn(address,uint256)": TypedContractEvent<
      StarsWithdrawnEvent.InputTuple,
      StarsWithdrawnEvent.OutputTuple,
      StarsWithdrawnEvent.OutputObject
    >;
    StarsWithdrawn: TypedContractEvent<
      StarsWithdrawnEvent.InputTuple,
      StarsWithdrawnEvent.OutputTuple,
      StarsWithdrawnEvent.OutputObject
    >;
  };
}
